### ISSUE TITLE
IETF language tags as file names

### ISSUE THREAD

**Issue by DanielBiegler** [DanielBiegler/pannellum-translation#34]
The author of Pannellum, @mpetroff, [mentioned](https://github.com/mpetroff/pannellum/pull/486#issuecomment-333394690) that one could use the IETF language tags instead of the currently used ISO 3166 ones. 

I'm not against this. If someone wants to do this, go ahead and make a PR.

**Comment by strarsis** [comment]
IETF language tags list: https://datahub.io/core/language-codes#resource-ietf-language-tags
ISO 3166 list: https://datahub.io/core/country-list

But aren't these tags basically the same? Doesn't it make only sense when dialects are used?
