### ISSUE TITLE
Add to npm?

### ISSUE THREAD

**Issue by strarsis** [DanielBiegler/pannellum-translation#39]
I am already using webpack for bundling pannellum. It would be nice of course if the translation files can also be loaded by webpack and then just passed to pannellum.
Publishing this on npm would be nice or at least adding a package.json.

**Comment by DanielBiegler** [comment]
Thats an excellent idea, will do!

**Comment by DanielBiegler** [comment]
Done! I hope everything is correct? Please let me know, I'll be glad to help. You can find the package here: https://www.npmjs.com/package/pannellum-translation

**Comment by DanielBiegler** [comment]
Also I added the package.json here on commit 0490208

**Comment by strarsis** [comment]
For webpack (locale 'DE' in this example):
````
$ yarn add pannellum-translation
````
```js
import pannellumTranslationDE from 'pannellum-translation/DE.json';
````
