### ISSUE TITLE
add polish translation

### ISSUE THREAD

**Issue by DanielBiegler** [DanielBiegler/pannellum-translation#5]
Only native speakers, please.

**Comment by ljagiello** [comment]
PR: https://github.com/DanielBiegler/pannellum-translation/pull/17

**Comment by galczo5** [comment]
Also native speaker. It looks good.

**Comment by DanielBiegler** [comment]
Thanks to both of you. @galczo5 what do you think of the other polish one here: #12  ?

**Comment by DanielBiegler** [comment]
closed because #17 got merged
